- hosts: db
  become: true
  become_user: root
  pre_tasks:
    - shell: echo 'START":" Apache Airflow database configuration'
  roles:
    - staging/mysql
  post_tasks:
    - shell: echo 'END":" Apache Airflow database configuration'
