- name: Install required packages
  yum:
    name: {{item}}
    state: latest
    update_cache: true
  with items: epel
    gcc
    postgresql-libs
    postgresql-devel
    python3
    python3-devel
    python3-pip
    python3-psycopg2
